### ISSUE TITLE
How to use gaussian points?

### ISSUE THREAD

**Issue by RuihanLu** [imlixinyang/Director3D#6]
Congratulations on your outstanding work! The released code runs very well, and I appreciate your contribution to the community.

I am curious about what is stored in the .splat file. Is it a 3DGS point cloud? How can we read .splat files? I am trying to reconstruct a mesh, and since the point cloud from the .ply file doesn't look very good, I am exploring other options.

Thanks for any help.

**Comment by imlixinyang** [comment]
Thanks for your interest! 

The ``.splat`` file contains the same information as the ``.ply`` file. The former can be read using [this repo](https://github.com/antimatter15/splat), while the latter can be read using [3D Model in Gradio](https://www.gradio.app/docs/gradio/model3d). We also developed a modified demo that allows for simultaneous visualization of scenes and cameras, which will be released in the near future. The demo shows like this:

<img width="947" alt="图片1" src="https://github.com/imlixinyang/Director3D/assets/26456614/05ee22b8-b04a-4214-98c1-c907d418fe2b">

We have also noticed some issues with the generated 3DGS, such as over-large scales and hole-like artifacts in free viewpoints. Some of these issues can be mitigated by introducing random camera perturbations during the refining stage, while others may require new regularization techniques or a better formulation for pixel-aligned 3DGS. Although the visual quality is not significantly affected under the original trajectories, it could be detrimental to mesh extraction as you mentioned. We will continue to work on addressing these issues, so please stay tuned for updates.

**Comment by RuihanLu** [comment]
Thanks for your reply! This demo looks really well!
